namespace: throneteki-development
environment: development

image:
    repository: cryogen/throneteki-lobby
    tag: latest

deployTime: '0'

nodeConfig: {}

storage:
    className: local-path
    cardImages: 5Gi
    avatars: 1Gi

resources: {}

redirectMiddleware:
    create: true
    names:
        canonicalHost: redirect-canonical-host
